function init(self)
	msg.post(".", "acquire_input_focus")

	gui.set_text(gui.get_node("score_text"), "Score: 0")

	hide_fail_screen()
	hide_level_complete_screen()
	hide_victory_screen()
end

function hide_fail_screen()
	gui.set_enabled(gui.get_node("game_over_text"), false)
	gui.set_enabled(gui.get_node("restart_button"), false)
	gui.set_enabled(gui.get_node("restart_text"), false)
end

function show_fail_screen()
	gui.set_enabled(gui.get_node("game_over_text"), true)
	gui.set_enabled(gui.get_node("restart_button"), true)
	gui.set_enabled(gui.get_node("restart_text"), true)
end

function hide_level_complete_screen()
	gui.set_enabled(gui.get_node("level_complete_text"), false)
	gui.set_enabled(gui.get_node("next_button"), false)
	gui.set_enabled(gui.get_node("next_text"), false)
end

function show_level_complete_screen(score)
	gui.set_text(gui.get_node("level_complete_text"), "LEVEL 1 COMPLETE\nScore: " .. score)

	gui.set_enabled(gui.get_node("level_complete_text"), true)
	gui.set_enabled(gui.get_node("next_button"), true)
	gui.set_enabled(gui.get_node("next_text"), true)
end

function hide_victory_screen()
	gui.set_enabled(gui.get_node("victory_text"), false)
	gui.set_enabled(gui.get_node("replay_button"), false)
	gui.set_enabled(gui.get_node("replay_text"), false)
end

function show_victory_screen(score)
	gui.set_text(gui.get_node("victory_text"), "YOU WIN!\nFinal Score: " .. score)

	gui.set_enabled(gui.get_node("victory_text"), true)
	gui.set_enabled(gui.get_node("replay_button"), true)
	gui.set_enabled(gui.get_node("replay_text"), true)
end

function on_message(self, message_id, message)
	if message_id == hash("set_score") then
		gui.set_text(gui.get_node("score_text"), "Score: " .. message.score)

	elseif message_id == hash("show_restart") then
		show_fail_screen()

	elseif message_id == hash("show_level_complete") then
		show_level_complete_screen(message.score)

	elseif message_id == hash("show_victory") then
		show_victory_screen(message.score)
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then

		if gui.pick_node(gui.get_node("restart_button"), action.x, action.y) then
			msg.post("@system:", "reboot")
		end

		if gui.pick_node(gui.get_node("next_button"), action.x, action.y) then
			hide_level_complete_screen()
			msg.post("/player#player", "start_level2")
		end

		if gui.pick_node(gui.get_node("replay_button"), action.x, action.y) then
			msg.post("@system:", "reboot")
		end
	end
end