function init(self)
	msg.post(".", "acquire_input_focus")
	gui.set_enabled(gui.get_node("button"), false)
end

function on_message(self, message_id, message)
	if message_id == hash("show_restart") then
		gui.set_enabled(gui.get_node("button"), true)
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		local button = gui.get_node("button")
		if gui.pick_node(button, action.x, action.y) then
			msg.post("@system:", "reboot")
		end
	end
end